### ISSUE TITLE
[BUG] Missing warning for "SSCN" and "FMCN" bus speed config

### ISSUE THREAD

**Issue by dreamwhite** [williambj1/GenI2C#20]
**SPECS**
- **MOBO** Dell Inspiron 5370
- **CPU** i5-8250U
- **GPU** Intel Graphics UHD 620
- **TRACKPAD**

![image](https://user-images.githubusercontent.com/17933708/79224239-09d06f00-7e5b-11ea-95ad-f1db45a38e94.png)

I was testing about `SSCN` and `FMCN` bus speed config when I've realized that they're missing inside origin/DSDT.aml. GenI2C isn't reporting this as you can see from the screenshot below:

![image](https://user-images.githubusercontent.com/17933708/79223673-143e3900-7e5a-11ea-98c0-f418f689aa68.png)

Also, as @alexandred said thousand times, `AppleIntelLpsssI2C` and `AppleIntelLpsssI2CController` are automatically disabled starting from VoodooI2C v. 2.3, without need of Coolstar I2C patches. 
GenI2C reports that they aren't disabled, but trackpad is working.

Below the output of `kextstat` saying the opposite of GenI2C :) 

![image](https://user-images.githubusercontent.com/17933708/79224078-cf66d200-7e5a-11ea-998b-576a9ab6e04d.png)

I dumped the logs from dmesg and you can see the two logs, with and without `SSCN` and `FMCN` bus speed config

[log_without_sscn_fmcn.txt](https://github.com/williambj1/GenI2C/files/4475159/log_without_sscn_fmcn.txt)
[log_with_sscn_fmcn.txt](https://github.com/williambj1/GenI2C/files/4475160/log_with_sscn_fmnc.txt)

Hope to fix this asap

- dreamwhite

**Comment by williambj1** [comment]
8250U doesn't need the bus speed patches, the original values hardcoded in VoodooI2C should work fine. That's why it's labeled as a warning, not an error, The reason of why you're still receiving this warning is because you only patched it for one controller but in 9D61, it still exists (I'm sure you removed the logs for 9D61, please don't do that again.)

Please provide a rigid VoodooI2C recommend troubleshooting achieve since I can't reproduce your issue of kext blocking detection.

**Comment by williambj1** [comment]
Closed since there’s no further conversation.
