### ISSUE TITLE
Need guide on how to patch VoodooI2C (Rog Strix G Series)

### ISSUE THREAD

**Issue by t3s8r8** [williambj1/GenI2C#26]
Hi, last time I remembered we discussed about patching USB ports on my Rog Strix G and OpenCore support from yours. But it appears those posts about Rog Strix G and experimental OpenCore is removed. I don't know what happens, you no longer support for this Rog Strix G series ?

Anyway, good news that I acquired installing macOS (Big Sur) with OpenCore, transitioned completely from Clover, but I kind of confusing about patching VoodooI2C since Asus laptop (like Rog...) may hard to patch and use.
I wonder if you still support the Rog Strix G models, if possbile, I think not only me but others need guide on how to patch VoodooI2C because you may the only one who can support and simplified the process of patching.

Thanks, hope you reply, have a nice day.

**Comment by williambj1** [comment]
Hi, @t3s8r8 sorry for the late reply, I was extremely busy these days.

First, to clarify, I never provided support for the Strix series. I do have some experience with the Zephyrus series but not with the newer models released after mid-2019. The repo was removed because I don't have much time to maintain it, and I did not want to create outdated, misleading information for others. I hope you can understand my situation.

Patching I2C with polling mode for ROG laptops are usually very simple, I'm glad that you finally got it working. Cheers for that!

Since this place is not really suitable for this type of conversation, I am going to close this issue. Feel free to contact me on Gitter at any time.

Thanks and have a nice day too.
